Repository KUIT-SweetBalance/SweetBalance-Web, pull requests merged in 2025-01, with the labels that each got.

#2 [Feat] #1 - 사용자 입력 처리 컴포넌트 생성 및 프로젝트 폴더 구조 변경
  .prettierrc
  eslint.config.js
  package-lock.json
  package.json
  src/App.tsx
  src/components/input/userDataInput/UserDataInput.styled.tsx
  src/components/input/userDataInput/UserDataInput.tsx
  src/pages/main
  src/pages/onboarding/UserNickname.tsx
  src/pages/onboarding/UserPassword.tsx
Labels: Feat

#5 [Design] #4 - main page의 '오늘' 화면 디자인 완료
  src/App.tsx
  src/assets/bell.png
  src/assets/heart-filled.png
  src/assets/heart.png
  src/assets/line3.png
  src/components/appTitle/AppTitle.tsx
  src/components/drinkInfo/DrinkInfo.tsx
  src/components/input/userDataInput/UserDataInput.tsx
  src/pages/main/main-today/DailyIntake.tsx
  src/pages/main/main-today/Today.tsx
  src/pages/main/main-today/TodayWeekButton.tsx
Labels: Design, 지성

#9 [Design, Feat] #7 - 메인화면 디자인 및 사용자 입력 컴포넌트 추가
  package-lock.json
  package.json
  src/App.tsx
  src/assets/magnifyingglass.png
  src/assets/visibility.png
  src/components/appTitle/AppTitle.tsx
  src/components/drinkInfo/DrinkInfo.tsx
  src/components/input/searchInput/SearchInput.tsx
  src/components/input/userDataInput/UserDataInput.styled.tsx
  src/components/input/userDataInput/UserDataInput.tsx
  src/pages/custom/custom-main/custom.tsx
  src/pages/main/home/Home.tsx
  src/pages/main/home/TodayWeekSwitcher.tsx
  src/pages/main/main-today/DailyInfo.tsx
  src/pages/main/main-today/DailyIntake.tsx
  src/pages/main/main-week/WeeklyInfo.tsx
  src/pages/main/main-week/WeeklyIntake.tsx
  src/pages/main/main-week/WeeklyStats.tsx
  src/pages/onboarding/UserNickname.tsx
  src/pages/onboarding/UserPassword.tsx
  src/pages/search/searchDrink/SearchDrink.tsx
  tailwind.config.js
Labels: Design, Feat, 지성

#12 [Design] #10 - main관련 화면 디자인 및 Router 적용
  index.html
  src/App.tsx
  src/assets/chevron-left.png
  src/assets/edit-completed.png
  src/components/appTitle/AppTitle.tsx
  src/components/drinkInfo/DrinkInfo.tsx
  src/components/header/NavigateHeader.tsx
  src/components/modal/Modal.tsx
  src/components/tabBar/TabBar.tsx
  src/index.css
  src/pages/main/alarm/Alarm.tsx
  src/pages/main/alarm/AlarmItem.tsx
  src/pages/main/edit/EditCompleted.tsx
  src/pages/main/edit/EditDrink.tsx
  src/pages/main/home/Home.tsx
  src/pages/main/home/TodayWeekSwitcher.tsx
  src/pages/main/home/home-today/DailyInfo.tsx
  src/pages/main/home/home-today/DailyIntake.tsx
  src/pages/main/home/home-week/WeeklyInfo.tsx
  src/pages/main/home/home-week/WeeklyIntake.tsx
  src/pages/main/home/home-week/WeeklyStats.tsx
  src/pages/main/main-today/DailyInfo.tsx
  src/pages/main/modal/EditDrinkModal.tsx
  src/pages/main/modal/LargeFavoriteDrinkModal.tsx
  src/pages/main/modal/SmallFavoriteDrinkModal.tsx
  src/pages/search/searchDrink/SearchDrink.tsx
  src/router/Router.tsx
  tailwind.config.js
Labels: Design, Feat, 지성

#15 [Feat] #8 - 버튼 컴포넌트 생성
  src/components/button/Button.tsx
  src/pages/custom/custom-main/custom.tsx
  tailwind.config.js
Labels: Feat, 지예
