Repository KUIT-SweetBalance/SweetBalance-Web, pull requests merged in 2025-02, with the labels that each got.

#26 [Design] 온보딩 페이지 구현
  src/assets/logo.svg
  src/assets/onboarding/kakao_logo.svg
  src/assets/onboarding/login_logo.svg
  src/assets/onboarding/login_text.svg
  src/assets/onboarding/onboarding1_icon.svg
  src/assets/onboarding/onboarding1_logo.svg
  src/assets/onboarding/sign_in_step1.svg
  src/assets/onboarding/sign_in_step2.svg
  src/assets/onboarding/sign_in_step3.svg
  src/assets/onboarding/sign_in_step4.svg
  src/components/button/Button.tsx
  src/components/input/userDataInput/UserDataInput.tsx
  src/pages/onboarding/Kakaotalk/apiClient.tsx
  src/pages/onboarding/UserNickname.tsx
  src/pages/onboarding/UserPassword.tsx
  src/pages/onboarding/auth-selection/AuthSelection.tsx
  src/pages/onboarding/login/ForgotPassword.tsx
  src/pages/onboarding/login/Login.tsx
  src/pages/onboarding/sign-in/SignIn.tsx
  src/pages/onboarding/splash/Splash.tsx
  src/router/Router.tsx
Labels: Design, 지예

#27 [Feat, Design] API 관련 사전작업 진행 및 메인화면 리디자인 적용
  package-lock.json
  package.json
  public/DrinkSugar.png
  public/bell.png
  public/bell2.png
  public/chevron-left.png
  public/chevron-right.png
  public/star-filled.png
  public/star.png
  public/sugar_angry.png
  public/sugar_heart.png
  src/App.tsx
  src/api/ApiManager.ts
  src/api/apis/example/Example.ts
  src/api/apis/example/UserListTest.tsx
  src/api/apis/example/UserListTest2.tsx
  src/api/apis/example/UserListTest3.tsx
  src/components/BottomNavi/BottomNavi.tsx
  src/main.tsx
  src/pages/main/edit/EditCompleted.tsx
  src/pages/main/edit/SugarProgressCircle.tsx
  src/pages/main/home/Home.tsx
  src/pages/main/home2/Home2.tsx
  src/pages/main/home2/Today/DrinkCard.tsx
  src/pages/main/home2/Today/Home2TodayBody.tsx
  src/pages/main/home2/Today/Home2TodayHeader.tsx
  src/pages/main/home2/TodayWeekSwitcher.tsx
  src/pages/main/home2/Weekly/Home2WeeklyBody.tsx
  src/pages/main/home2/Weekly/Home2WeeklyHeader.tsx
  src/pages/main/home2/Weekly/WeeklyIntakeStatBox.tsx
  src/pages/main/home2/Weekly/WeeklySugarChart.tsx
  src/pages/main/search/BrandSearchResult.tsx
  src/router/Router.tsx
Labels: Design, Feat, 지성

#29 [Feat] BottomNavi 탭뷰 기능 구현 및 Main화면 일부 navigation기능 구현
  public/chevron-left-primary.png
  src/components/BottomNavi/BottomNavi.tsx
  src/components/input/searchInput/SearchInput.tsx
  src/pages/main/edit/EditDrink.tsx
  src/pages/main/home2/Today/Home2TodayBody.tsx
  src/pages/main/search/AllBrands.tsx
  src/pages/main/search/BrandSearchResult.tsx
  src/pages/main/search/SearchDrink.tsx
  src/router/Router.tsx
  src/store/bottomNavi/BottomNaviIndex.ts
Labels: Feat, 지성

#34 [Feat] 로컬 환경에서 https를 사용할 수 있도록 세팅, API 요청 테스트 완료
  .gitignore
  public/brands/megacoffee.png
  public/brands/paik.png
  public/brands/starbucks.png
  src/api/ApiManager.ts
  src/api/apis/example/UserListTest2.tsx
  src/api/main/search/BrandSearchResult/BrandSearchResult.ts
  src/pages/main/edit/EditCompleted.tsx
  src/pages/main/edit/SugarProgressCircle.tsx
  src/pages/main/home2/Today/DrinkCard.tsx
  src/pages/main/search/BrandSearchResult.tsx
  src/pages/main/search/SearchDrink.tsx
  src/types/brands.ts
  vite.config.ts
Labels: Feat, Network, Setting, 지성

#36 [Feat] 메인 페이지 api 연결
  public/sugar/sugar_angry.png
  public/sugar/sugar_angry_big.png
  public/sugar/sugar_concern.png
  public/sugar/sugar_flower.png
  public/sugar/sugar_heart.png
  src/api/ApiManager.ts
  src/api/main/alarm/Alarm.ts
  src/api/main/home2/Today/Home2TodayBody.tsx
  src/api/main/home2/Today/Home2TodayHeader.ts
  src/api/main/home2/Weekly/Home2WeeklyHeader.ts
  src/api/main/search/BrandSearchResult/BrandSearchResult.ts
  src/api/main/search/DrinkList.ts
  src/components/drinkInfo/DrinkInfo.tsx
  src/components/noContents/NoContents.tsx
  src/pages/main/alarm/Alarm.tsx
  src/pages/main/alarm/AlarmItem.tsx
  src/pages/main/edit/EditDrink.tsx
  src/pages/main/home2/Home2.tsx
  src/pages/main/home2/Today/DrinkCard.tsx
  src/pages/main/home2/Today/Home2TodayBody.tsx
  src/pages/main/home2/Today/Home2TodayHeader.tsx
  src/pages/main/home2/Weekly/Home2WeeklyBody.tsx
  src/pages/main/home2/Weekly/Home2WeeklyHeader.tsx
  src/pages/main/home2/Weekly/WeeklyIntakeStatBox.tsx
  src/pages/main/home2/Weekly/WeeklySugarChart.tsx
  src/pages/main/modal/AlarmInfoModal.tsx
  src/pages/main/modal/LargeFavoriteDrinkModal.tsx
  src/pages/main/search/BrandSearchResult.tsx
  src/pages/main/search/SearchDrink.tsx
  src/store/modal/AlarmInfo.tsx
  src/store/modal/LargeFavoriteModalStore.ts
  src/types/drink.ts
Labels: Feat, 지성

#40 [Feat] #37 - Search탭 api 연결 완료
  src/api/main/search/DrinkList.ts
  src/components/drinkInfo/DrinkInfo.tsx
  src/components/noContents/NoContents.tsx
  src/hooks/useInfiniteScroll.ts
  src/pages/main/edit/EditDrink.tsx
  src/pages/main/home2/Today/Home2TodayBody.tsx
  src/pages/main/search/BrandSearchResult.tsx
  src/pages/main/search/DrinkSearchResult.tsx
  src/pages/main/search/SearchDrink.tsx
Labels: Feat, 지성

#47 [Setting] gh-pages 패키지 설치 및 package.json script 추가
  package-lock.json
  package.json
Labels: Setting, 지성

#51 Netlify 세팅 및 배포 완료, 메인화면 디자인 및 기능 수정, 온보딩 화면 디자인 수정, 규운 코드 머지
  eslint.config.js
  index.html
  package-lock.json
  package.json
  src/api/main/home2/Today/Home2TodayBody.tsx
  src/components/drinkInfo/DrinkInfo.tsx
  src/components/input/userDataInput/UserDataInput.tsx
  src/pages/main/edit/EditDrink.tsx
  src/pages/main/home2/Weekly/Home2WeeklyHeader.tsx
  src/pages/main/modal/AlarmInfoModal.tsx
  src/pages/main/search/AllBrands.tsx
  src/pages/main/search/BrandSearchResult.tsx
  src/pages/main/search/DrinkSearchResult.tsx
  src/pages/main/search/SearchDrink.tsx
  src/pages/onboarding/login/Login.tsx
  src/pages/onboarding/sign-in/SignIn.tsx
  src/types/drink.ts
  tsconfig.json
  vite.config.ts
Labels: Design, Feat, Setting, 지성

#55 다양한 수정사항
  src/api/ApiManager.ts
  src/api/onboarding/Login.ts
  src/components/button/Button.tsx
  src/components/drinkInfo/DrinkInfo.tsx
  src/pages/main/alarm/AlarmItem.tsx
  src/pages/main/edit/EditDrink.tsx
  src/pages/main/search/BrandSearchResult.tsx
  src/pages/main/search/SearchDrink.tsx
  src/pages/onboarding/login/ForgotPassword.tsx
  src/pages/onboarding/login/Login.tsx
  src/types/drink.ts
Labels: 지성

#69 [Feat] 비밀번호 재설정 화면 디자인 및 api 연동
  src/api/ApiManager.ts
  src/api/onboarding/Password.ts
  src/components/modal/Modal.tsx
  src/pages/main/alarm/Alarm.tsx
  src/pages/main/edit/EditDrink.tsx
  src/pages/main/home2/Today/Home2TodayHeader.tsx
  src/pages/main/home2/Weekly/Home2WeeklyBody.tsx
  src/pages/main/home2/Weekly/WeeklyIntakeStatBox.tsx
  src/pages/main/home2/Weekly/WeeklySugarChart.tsx
  src/pages/main/search/SearchDrink.tsx
  src/pages/mypage/mypage-record/Arrangement.tsx
  src/pages/mypage/mypage-record/MypageRecord.tsx
  src/pages/onboarding/login/ForgotPassword.tsx
  src/pages/onboarding/sign-in/KakaoSignIn.tsx
  src/pages/onboarding/sign-in/SignIn.tsx
Labels: Design, Feat, 지성

#70 [Fix] 마이페이지 무한스크롤 오류 수정 및 사소한 디자인 수정
  public/verticalBar.png
  src/pages/main/home2/Home2.tsx
  src/pages/mypage/mypage-record/MypageDrinkInfo.tsx
  src/pages/mypage/mypage-record/MypageRecord.tsx
  src/pages/mypage/mypage-scrap/MypageScrap.tsx
  src/pages/mypage/mypage-scrap/MypageScrapinfo.tsx
  src/pages/onboarding/login/Login.tsx
Labels: Fix, 지성

#76 [Chore] padding, margin 등 디자인 수정
  src/components/drinkInfo/DrinkInfo.tsx
  src/pages/main/alarm/Alarm.tsx
  src/pages/main/edit/EditDrink.tsx
  src/pages/main/home2/Today/Home2TodayHeader.tsx
  src/pages/onboarding/auth-selection/AuthSelection.tsx
Labels: Chore, 지성
